spring:
  application:
    name: novice-test #服务名称
  datasource:
    url: jdbc:mysql://192.168.152.128:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: mysql
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 5
    host: 192.168.152.128
    port: 6379
    password:
  cloud:
     stream:
        default:
          group: service

          contentType: application/json
          binder: kafka
          consumer:
            concurrency: 1 #消费者并发数
            partitioned: true
          producer:
            partitionKeyExpression: payload.id
            partitionCount: 1 #分区数
        instanceCount: 3 #微服务实例数
        kafka:
          binder:
            brokers: 192.168.152.129:9092
            replicationFactor: 1 #备份数
            autoAddPartitions: true
            autoCreateTopics: true
        bindings:
          task-input:
            destination: test
          task-output:
            destination: test

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.univer.*.po